version: '3.9'

services:
  # Dịch vụ Meilisearch
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    ports:
      # Ánh xạ cổng 7700 của container ra cổng 7700 của máy bạn
      - "7700:7700"
    volumes:
      # Lưu trữ dữ liệu của Meilisearch vào thư mục ./meili_data trên máy bạn
      - ./meili_data:/meili_data
    environment:
      # BẮT BUỘC: Đặt Master Key để bảo mật. Thay thế bằng key của riêng bạn!
      - MEILI_MASTER_KEY=CLwNNTw_zeA-XdXRmbvB5Oozy3iZc7RaQK9KpGMLB84
      # Môi trường development sẽ tắt yêu cầu master key cho một số endpoint (tiện cho phát triển)
      - MEILI_ENV=development
    restart: unless-stopped # Tự khởi động lại nếu bị dừng ngoài ý muốn

  # Dịch vụ Redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      # Ánh xạ cổng 6379 của container ra cổng 6379 của máy bạn
      # Tiện cho việc kết nối từ các công cụ quản lý Redis trên máy tính
      - "6379:6379"
    volumes:
      # Lưu trữ dữ liệu của Redis vào thư mục ./redis_data trên máy bạn
      - ./redis_data:/data
    restart: unless-stopped

    # === Dịch vụ RabbitMQ (MỚI THÊM) ===
  rabbitmq:
    # Sử dụng image có sẵn giao diện quản lý web, rất tiện lợi
    image: rabbitmq:3.13-management 
    container_name: rabbitmq
    ports:
      # Cổng 5672: Dành cho ứng dụng của bạn (Publisher/Consumer) kết nối tới
      - "5672:5672"
      # Cổng 15672: Dành cho giao diện quản lý trên trình duyệt web
      - "15672:15672"
    volumes:
      # Lưu trữ dữ liệu của RabbitMQ (queues, messages, users...) để không bị mất khi container khởi động lại
      - ./rabbitmq_data:/var/lib/rabbitmq
    environment:
      # Thiết lập user và password mặc định cho RabbitMQ
      # HÃY THAY THẾ BẰNG USER/PASSWORD CỦA BẠN ĐỂ BẢO MẬT HƠN
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    restart: unless-stopped